### ISSUE TITLE
Integrate seed balance in user overview

### ISSUE THREAD

**Issue by nielslange** [limikael/wp-seeds#11]

**Comment by limikael** [comment]
What is the "user overview"? And should this be implemented in the plugin? My thinking is that the plugin should just provide a few shortcodes as building blocks... And then these can be combined to create the user experience we want, but this is rather a questions of designing the pages and using the right shortcodes on the right pages... Not functionality in the shortcodes themselves... See how I mean?

**Comment by nielslange** [comment]
By _user overview_ I'm referring to the page on which all users are listed: http://limikael.altervista.org/seeds-staging/wp-admin/users.php

Currently, that page has the following columns:

- Username
- Name
- Email
- Role
- Posts

Here, I would add an extra column for the seed balance.

Regarding your question if this should be implemented within the plugin: Yes, absolutely! If a user deactivates the plugin, all these fields no longer are displayed, therefore, it's the job of the plugin to enhance WordPress with everything needed.

**Comment by nielslange** [comment]
Reopen issue due to minor bug fix.
