### ISSUE TITLE
Link seed balance on users overview page to transaction history of user

### ISSUE THREAD

**Issue by nielslange** [limikael/wp-seeds#13]

**Comment by limikael** [comment]
My initial thinking is that this functionality doesn't have to be in the plugin itself. It is easy to add a link around the shortcode when the balance is shown. I updated the "My Account" page so the balance is now a link:

![image](https://user-images.githubusercontent.com/902911/64071324-8e92c200-ccaa-11e9-9f81-36a22c4fc51a.png)

Does this solve the issue or should it rather be implemented in the plugin somehow?

**Comment by nielslange** [comment]
That looks indeed great. In addition, I would also add the fields to WP Admin itself. I'll implement it to show you what I mean. :P

**Comment by nielslange** [comment]
Related to https://github.com/limikael/wp-seeds/issues/12#issuecomment-527166575

**Comment by nielslange** [comment]
Close issue as this feature had been implemented in https://github.com/limikael/wp-seeds/commit/5ab2466ff09c2b76723ece30c725d11a30d3c50d.
