### ISSUE TITLE
Enable QR code based transactions

### ISSUE THREAD

**Issue by nielslange** [limikael/wp-seeds#14]
**Case 1: Customer gets seeds from merchant**

As customer
I want to be able to scan a QR code
So that I retrieve seeds from the merchant.

**Case 2: Merchant offers seeds to customer**

As merchant
I want to be able to generate a QR code
So that a customer gets seeds for a purchase.

**Case 3: Customers gets seeds from customer**

As customer
I want to be able to scan a QR code
So that I retrieve seeds from another customer.

**Case 4: Customers offers seeds to customer**

As customer
I want to be able to generate a QR code
So that a customer gets seeds from me.

**Comment by limikael** [comment]
Yep :+1: The QR code should include information so it becomes a "payment request", so it will have information in it about the destination account, as well as the amount and information about what the payment is for... As a customer I can then scan the QR code and click accept.

**Comment by limikael** [comment]
Did some research on reqding qr codes... Some libraries:

* https://github.com/LazarSoft/jsqrcode Demo at: https://webqr.in/
* https://github.com/schmich/instascan

However! I tested it and it works very well on Android, but it seems that this relies on technology that isn't fully implemented on iPhone... :( Some references:

* https://www.quora.com/Can-mobile-browsers-like-safari-or-Chrome-open-smartphone-cameras-as-well-as-the-microphone
* https://bugs.chromium.org/p/chromium/issues/detail?id=752458
* https://stackoverflow.com/questions/51501642/chrome-and-firefox-are-not-able-to-access-iphone-camera

There is a fallback though... Not as nice user experience, but still works:

https://www.sitepoint.com/create-qr-code-reader-mobile-website/

So with some twiddling, it would be possible to create something that checks the browser and chooses the most suitable version.

**Comment by nielslange** [comment]
I would say we only need a specific URL, e.g. `/?from={SENDER}&to={RECEIVER}&seeds={AMOUNT}&auth={TOKEN}` and the convert that URL to a QR code. 

As this issue has a very low priority for the moment, I suggest that we sit together in October and analyse options when we meet in person.

**Comment by limikael** [comment]
sounds good

**Comment by nielslange** [comment]
Close issue as this had been implemented in https://github.com/limikael/wp-seeds/pull/58.
