### ISSUE TITLE
Create a composer task to run code-sniffer

### ISSUE THREAD

**Issue by limikael** [limikael/wp-seeds#44]
...as it says... :)

**Comment by nielslange** [comment]
That's what I run in the terminal:

```
phpcs . --ignore=class-tgm-plugin-activation.php --standard=WordPress
```

And that's how the Twenty Twenty theme runs PHPCS and WPCS:

https://github.com/WordPress/twentytwenty/blob/bc89c516bbb13b61d32848c2f021afc532c3810d/composer.json#L20-L29 and https://github.com/WordPress/twentytwenty/blob/bc89c516bbb13b61d32848c2f021afc532c3810d/.travis.yml#L48
