### ISSUE TITLE
Remove empty select option on create new seeds page

### ISSUE THREAD

**Issue by nielslange** [limikael/wp-seeds#5]
**Steps to reproduce**

1. Go to http://limikael.altervista.org/seeds-staging/wp-admin/admin.php?page=seeds_create
2. Click on select field _Select User Account_

**Expected behaviour**

- Only existing user accounts are visible.

**Current behaviour**

- Between _Select User Account_ and the existing user accounts, there's an empty entry visible, see screenshot below.

<img width="570" alt="Screenshot 2019-08-31 at 16 00 10" src="https://user-images.githubusercontent.com/3323310/64061692-74080c80-cc08-11e9-9844-2d5d8c4f7240.png">

**Comment by nielslange** [comment]
Seems the fix went sideways. Please try again, @nielslange! 😂

**Comment by limikael** [comment]
This is in fact by design... Just to make some space between the prompt and the list... The line that does it is here:

https://github.com/limikael/wp-seeds/blob/master/tpl/seeds_create.tpl.php#L45

Might not be "good design" even though it is design... So I'm fine with removing it...

**Comment by nielslange** [comment]
Thanks for explaining the design reason behind it. I removed it due to usability aspects and to follow the default WordPress behavior. By keeping the plugin as close to the default WordPress behavior users can reuse learned patters. I also removed the empty fields on other forms and would follow that approach here. 😀

**Comment by limikael** [comment]
Ok that makes sense! I checked the create seeds page, and I saw that the empty option was still there... I removed it, here is the commit:

https://github.com/limikael/wp-seeds/commit/fee5f778b5bf84e5879faaf171b7843a322748dd

(made a some other cleanups as well...)
